/**
 * ════════════════════════════════════════════════════════════════
 * src/modules/expected_deliveries.js — v0.1 (PARÇA 1: veri modeli + helper + mode + validation)
 * EXPECTED-DELIVERIES-FLOW-002
 * ════════════════════════════════════════════════════════════════
 */
(function() {
  'use strict';

  /* ─── MODE GUARD ──────────────────────────────────────────── */
  window.EXPECTED_DELIVERIES_MODE = window.EXPECTED_DELIVERIES_MODE || 'MANUAL_MODE';

  window._edIsAutoMode = function() {
    return window.EXPECTED_DELIVERIES_MODE === 'AUTO_MODE';
  };

  window._edCanManualCreate = function() {
    if (window._edIsAutoMode()) {
      var cu = (window.CU && window.CU()) || {};
      return (cu.role || cu.rol) === 'admin';
    }
    return true;
  };

  /* ─── COMPUTED HELPERS ────────────────────────────────────── */
  window._edCalculateDelivered = function(ed) {
    if (!ed || !Array.isArray(ed.deliveries)) return 0;
    return ed.deliveries.reduce(function(sum, d) { return sum + (parseFloat(d && d.qty) || 0); }, 0);
  };

  window._edCalculateRemaining = function(ed) {
    var total = parseFloat(ed && ed.quantityTotal) || 0;
    return Math.max(0, total - window._edCalculateDelivered(ed));
  };

  window._edCalculateDelay = function(ed) {
    if (!ed || !ed.estimatedDeliveryDate) return 0;
    var est = new Date(ed.estimatedDeliveryDate).getTime();
    if (isNaN(est)) return 0;
    return Math.floor((Date.now() - est) / 86400000);
  };

  window._edIsOverdue = function(ed) {
    var delay = window._edCalculateDelay(ed);
    var tolerance = parseInt(ed && ed.toleranceDays, 10);
    if (isNaN(tolerance)) tolerance = 0;
    return delay > tolerance;
  };

  window._edCalculateRemainingDays = function(ed) {
    if (!ed || !ed.estimatedDeliveryDate) return null;
    var est = new Date(ed.estimatedDeliveryDate).getTime();
    if (isNaN(est)) return null;
    return Math.ceil((est - Date.now()) / 86400000);
  };

  window._edEnrich = function(ed) {
    if (!ed) return ed;
    ed.quantityDelivered = window._edCalculateDelivered(ed);
    ed.quantityRemaining = window._edCalculateRemaining(ed);
    ed.remainingDays = window._edCalculateRemainingDays(ed);
    if (window._edIsOverdue(ed) && ed.status !== 'TESLIM_ALINDI') {
      ed.status = 'GECIKTI';
    }
    return ed;
  };

  /* ─── VALIDATION ──────────────────────────────────────────── */
  var PRIORITIES = ['LOW', 'NORMAL', 'CRITICAL'];
  var STATUSES = ['TEDARIK_ASAMASINDA','URETIMDE','YUKLEME_BEKLIYOR','YOLDA','GUMRUKTE','TESLIM_ALINDI','GECIKTI'];
  var DELAY_OWNERS = ['supplier', 'logistics', 'internal'];

  window._edValidate = function(ed) {
    var errors = [];
    if (!ed) return { valid: false, errors: ['Kayıt boş'] };

    if (!ed.productName) errors.push('Ürün adı zorunlu');
    if (!ed.supplierId) errors.push('Tedarikçi zorunlu');
    if (!ed.responsibleUserId) errors.push('Sorumlu kullanıcı zorunlu');
    if (!ed.responsibleRole) errors.push('Sorumlu rol zorunlu');

    var qty = parseFloat(ed.quantityTotal);
    if (!qty || qty <= 0) errors.push('Miktar 0\'dan büyük olmalı');

    if (ed.proformaDate && ed.estimatedDeliveryDate) {
      if (new Date(ed.proformaDate) > new Date(ed.estimatedDeliveryDate)) {
        errors.push('Proforma tarihi, tahmini teslim tarihinden sonra olamaz');
      }
    }
    if (ed.actualShipmentDate && ed.actualDeliveryDate) {
      if (new Date(ed.actualShipmentDate) > new Date(ed.actualDeliveryDate)) {
        errors.push('Sevk tarihi, teslim tarihinden sonra olamaz');
      }
    }

    if (ed.priority && PRIORITIES.indexOf(ed.priority) === -1) errors.push('Geçersiz öncelik (LOW/NORMAL/CRITICAL)');
    if (ed.status && STATUSES.indexOf(ed.status) === -1) errors.push('Geçersiz durum');
    if (ed.delayOwner && DELAY_OWNERS.indexOf(ed.delayOwner) === -1) errors.push('Geçersiz gecikme sorumlusu');

    return { valid: errors.length === 0, errors: errors };
  };

  /* ─── CREATE / UPDATE / DELETE WRAPPERS ───────────────────── */
  window._edCreate = function(ed) {
    if (!window._edCanManualCreate()) {
      window.toast && window.toast('AUTO_MODE aktif — manuel giriş için admin yetki gerekli', 'err');
      return { success: false, error: 'mode_restricted' };
    }

    ed = ed || {};
    var v = window._edValidate(ed);
    if (!v.valid) {
      window.toast && window.toast('Eksik: ' + v.errors.join(', '), 'err');
      return { success: false, errors: v.errors };
    }

    var cu = (window.CU && window.CU()) || {};
    ed.id = ed.id || ('ed_' + Date.now() + '_' + Math.random().toString(36).slice(2, 7));
    ed.createdAt = ed.createdAt || new Date().toISOString();
    ed.updatedAt = new Date().toISOString();
    ed.createdById = cu.id || cu.uid || 'bilinmiyor';
    ed.isDeleted = false;
    ed.autoGenerated = !!ed.autoGenerated;

    if (!ed.priority) ed.priority = 'NORMAL';
    if (!ed.status) ed.status = 'TEDARIK_ASAMASINDA';
    if (!Array.isArray(ed.deliveries)) ed.deliveries = [];
    if (ed.toleranceDays === undefined || ed.toleranceDays === null) ed.toleranceDays = 3;

    window._edEnrich(ed);

    var list = (typeof window.loadExpectedDeliveries === 'function' ? window.loadExpectedDeliveries({ raw: true }) : []) || [];
    list.push(ed);
    if (typeof window.storeExpectedDeliveries === 'function') window.storeExpectedDeliveries(list);

    try {
      if (typeof window.logActivity === 'function') {
        window.logActivity('expected_delivery_created', { edId: ed.id, productName: ed.productName, supplierId: ed.supplierId });
      }
    } catch(e) {}

    return { success: true, ed: ed };
  };

  window._edUpdate = function(edId, patch) {
    if (!edId) return { success: false, error: 'id_missing' };
    var list = (typeof window.loadExpectedDeliveries === 'function' ? window.loadExpectedDeliveries({ raw: true }) : []) || [];
    var idx = -1;
    for (var i = 0; i < list.length; i++) { if (list[i].id === edId) { idx = i; break; } }
    if (idx === -1) return { success: false, error: 'not_found' };

    var merged = Object.assign({}, list[idx], patch || {});
    merged.updatedAt = new Date().toISOString();

    var v = window._edValidate(merged);
    if (!v.valid) return { success: false, errors: v.errors };

    window._edEnrich(merged);
    list[idx] = merged;
    if (typeof window.storeExpectedDeliveries === 'function') window.storeExpectedDeliveries(list);
    return { success: true, ed: merged };
  };

  window._edDelete = function(edId) {
    if (!edId) return false;
    var list = (typeof window.loadExpectedDeliveries === 'function' ? window.loadExpectedDeliveries({ raw: true }) : []) || [];
    var idx = -1;
    for (var i = 0; i < list.length; i++) { if (list[i].id === edId) { idx = i; break; } }
    if (idx === -1) return false;
    list[idx].isDeleted = true;
    list[idx].updatedAt = new Date().toISOString();
    if (typeof window.storeExpectedDeliveries === 'function') window.storeExpectedDeliveries(list);
    return true;
  };
})();
