/**
 * ════════════════════════════════════════════════════════════════
 * src/modules/expected_deliveries.js — v0.1 (PARÇA 1: veri modeli + helper + mode + validation)
 * EXPECTED-DELIVERIES-FLOW-002
 * ════════════════════════════════════════════════════════════════
 */
(function() {
  'use strict';

  /* ─── MODE GUARD ──────────────────────────────────────────── */
  window.EXPECTED_DELIVERIES_MODE = window.EXPECTED_DELIVERIES_MODE || 'MANUAL_MODE';

  window._edIsAutoMode = function() {
    return window.EXPECTED_DELIVERIES_MODE === 'AUTO_MODE';
  };

  window._edCanManualCreate = function() {
    if (window._edIsAutoMode()) {
      var cu = (window.CU && window.CU()) || {};
      return (cu.role || cu.rol) === 'admin';
    }
    return true;
  };

  /* ─── COMPUTED HELPERS ────────────────────────────────────── */
  window._edCalculateDelivered = function(ed) {
    if (!ed || !Array.isArray(ed.deliveries)) return 0;
    return ed.deliveries.reduce(function(sum, d) { return sum + (parseFloat(d && d.qty) || 0); }, 0);
  };

  window._edCalculateRemaining = function(ed) {
    var total = parseFloat(ed && ed.quantityTotal) || 0;
    return Math.max(0, total - window._edCalculateDelivered(ed));
  };

  window._edCalculateDelay = function(ed) {
    if (!ed || !ed.estimatedDeliveryDate) return 0;
    var est = new Date(ed.estimatedDeliveryDate).getTime();
    if (isNaN(est)) return 0;
    return Math.floor((Date.now() - est) / 86400000);
  };

  window._edIsOverdue = function(ed) {
    var delay = window._edCalculateDelay(ed);
    var tolerance = parseInt(ed && ed.toleranceDays, 10);
    if (isNaN(tolerance)) tolerance = 0;
    return delay > tolerance;
  };

  window._edCalculateRemainingDays = function(ed) {
    if (!ed || !ed.estimatedDeliveryDate) return null;
    var est = new Date(ed.estimatedDeliveryDate).getTime();
    if (isNaN(est)) return null;
    return Math.ceil((est - Date.now()) / 86400000);
  };

  window._edEnrich = function(ed) {
    if (!ed) return ed;
    ed.quantityDelivered = window._edCalculateDelivered(ed);
    ed.quantityRemaining = window._edCalculateRemaining(ed);
    ed.remainingDays = window._edCalculateRemainingDays(ed);
    if (window._edIsOverdue(ed) && ed.status !== 'TESLIM_ALINDI') {
      ed.status = 'GECIKTI';
    }
    return ed;
  };

  /* ─── VALIDATION ──────────────────────────────────────────── */
  var PRIORITIES = ['LOW', 'NORMAL', 'CRITICAL'];
  var STATUSES = ['TEDARIK_ASAMASINDA','URETIMDE','YUKLEME_BEKLIYOR','YOLDA','GUMRUKTE','TESLIM_ALINDI','GECIKTI'];
  var DELAY_OWNERS = ['supplier', 'logistics', 'internal'];

  window._edValidate = function(ed) {
    var errors = [];
    if (!ed) return { valid: false, errors: ['Kayıt boş'] };

    if (!ed.productName) errors.push('Ürün adı zorunlu');
    if (!ed.supplierId) errors.push('Tedarikçi zorunlu');
    if (!ed.responsibleUserId) errors.push('Sorumlu kullanıcı zorunlu');
    if (!ed.responsibleRole) errors.push('Sorumlu rol zorunlu');

    var qty = parseFloat(ed.quantityTotal);
    if (!qty || qty <= 0) errors.push('Miktar 0\'dan büyük olmalı');

    if (ed.proformaDate && ed.estimatedDeliveryDate) {
      if (new Date(ed.proformaDate) > new Date(ed.estimatedDeliveryDate)) {
        errors.push('Proforma tarihi, tahmini teslim tarihinden sonra olamaz');
      }
    }
    if (ed.actualShipmentDate && ed.actualDeliveryDate) {
      if (new Date(ed.actualShipmentDate) > new Date(ed.actualDeliveryDate)) {
        errors.push('Sevk tarihi, teslim tarihinden sonra olamaz');
      }
    }

    if (ed.priority && PRIORITIES.indexOf(ed.priority) === -1) errors.push('Geçersiz öncelik (LOW/NORMAL/CRITICAL)');
    if (ed.status && STATUSES.indexOf(ed.status) === -1) errors.push('Geçersiz durum');
    if (ed.delayOwner && DELAY_OWNERS.indexOf(ed.delayOwner) === -1) errors.push('Geçersiz gecikme sorumlusu');

    return { valid: errors.length === 0, errors: errors };
  };

  /* ─── CREATE / UPDATE / DELETE WRAPPERS ───────────────────── */
  window._edCreate = function(ed) {
    if (!window._edCanManualCreate()) {
      window.toast && window.toast('AUTO_MODE aktif — manuel giriş için admin yetki gerekli', 'err');
      return { success: false, error: 'mode_restricted' };
    }

    ed = ed || {};
    var v = window._edValidate(ed);
    if (!v.valid) {
      window.toast && window.toast('Eksik: ' + v.errors.join(', '), 'err');
      return { success: false, errors: v.errors };
    }

    var cu = (window.CU && window.CU()) || {};
    ed.id = ed.id || ('ed_' + Date.now() + '_' + Math.random().toString(36).slice(2, 7));
    ed.createdAt = ed.createdAt || new Date().toISOString();
    ed.updatedAt = new Date().toISOString();
    ed.createdById = cu.id || cu.uid || 'bilinmiyor';
    ed.isDeleted = false;
    ed.autoGenerated = !!ed.autoGenerated;

    if (!ed.priority) ed.priority = 'NORMAL';
    if (!ed.status) ed.status = 'TEDARIK_ASAMASINDA';
    if (!Array.isArray(ed.deliveries)) ed.deliveries = [];
    if (ed.toleranceDays === undefined || ed.toleranceDays === null) ed.toleranceDays = 3;

    window._edEnrich(ed);

    var list = (typeof window.loadExpectedDeliveries === 'function' ? window.loadExpectedDeliveries({ raw: true }) : []) || [];
    list.push(ed);
    if (typeof window.storeExpectedDeliveries === 'function') window.storeExpectedDeliveries(list);

    try {
      if (typeof window.logActivity === 'function') {
        window.logActivity('expected_delivery_created', { edId: ed.id, productName: ed.productName, supplierId: ed.supplierId });
      }
    } catch(e) {}

    return { success: true, ed: ed };
  };

  window._edUpdate = function(edId, patch) {
    if (!edId) return { success: false, error: 'id_missing' };
    var list = (typeof window.loadExpectedDeliveries === 'function' ? window.loadExpectedDeliveries({ raw: true }) : []) || [];
    var idx = -1;
    for (var i = 0; i < list.length; i++) { if (list[i].id === edId) { idx = i; break; } }
    if (idx === -1) return { success: false, error: 'not_found' };

    var merged = Object.assign({}, list[idx], patch || {});
    merged.updatedAt = new Date().toISOString();

    var v = window._edValidate(merged);
    if (!v.valid) return { success: false, errors: v.errors };

    window._edEnrich(merged);
    list[idx] = merged;
    if (typeof window.storeExpectedDeliveries === 'function') window.storeExpectedDeliveries(list);
    return { success: true, ed: merged };
  };

  window._edDelete = function(edId) {
    if (!edId) return false;
    var list = (typeof window.loadExpectedDeliveries === 'function' ? window.loadExpectedDeliveries({ raw: true }) : []) || [];
    var idx = -1;
    for (var i = 0; i < list.length; i++) { if (list[i].id === edId) { idx = i; break; } }
    if (idx === -1) return false;
    list[idx].isDeleted = true;
    list[idx].updatedAt = new Date().toISOString();
    if (typeof window.storeExpectedDeliveries === 'function') window.storeExpectedDeliveries(list);
    return true;
  };

  /* ─── PARÇA 2: DELIVERY MANAGEMENT ──────────────────────── */
  var _edFindRaw = function(edId) {
    var list = (typeof window.loadExpectedDeliveries === 'function' ? window.loadExpectedDeliveries({ raw: true }) : []) || [];
    for (var i = 0; i < list.length; i++) { if (list[i].id === edId) return { list: list, idx: i }; }
    return { list: list, idx: -1 };
  };

  window._edAddDelivery = function(edId, delivery) {
    if (!delivery || typeof delivery.qty !== 'number' || delivery.qty <= 0) {
      return { success: false, error: 'Geçersiz miktar (qty > 0 olmalı)' };
    }
    var f = _edFindRaw(edId);
    if (f.idx === -1) return { success: false, error: 'not_found' };
    var ed = f.list[f.idx];
    if (!Array.isArray(ed.deliveries)) ed.deliveries = [];

    var delivered = window._edCalculateDelivered(ed);
    var remaining = (parseFloat(ed.quantityTotal) || 0) - delivered;
    if (delivery.qty > remaining) {
      return { success: false, error: 'Miktar kalan sınırını aşıyor (kalan: ' + remaining + ', eklenen: ' + delivery.qty + ')' };
    }

    delivery.status = delivery.status || 'shipped';
    delivery.shipmentDate = delivery.shipmentDate || new Date().toISOString();
    delivery.addedAt = new Date().toISOString();

    ed.deliveries.push(delivery);
    ed.updatedAt = new Date().toISOString();

    if (!ed.actualShipmentDate && delivery.shipmentDate) {
      ed.actualShipmentDate = delivery.shipmentDate;
      if (ed.status === 'TEDARIK_ASAMASINDA' || ed.status === 'URETIMDE') ed.status = 'YOLDA';
    }

    window._edEnrich(ed);
    f.list[f.idx] = ed;
    if (typeof window.storeExpectedDeliveries === 'function') window.storeExpectedDeliveries(f.list);

    try { if (typeof window.logActivity === 'function') window.logActivity('expected_delivery_partial_added', { edId: edId, qty: delivery.qty }); } catch(e) {}
    return { success: true, ed: ed };
  };

  window._edMarkDelivered = function(edId, deliveryIdx) {
    var f = _edFindRaw(edId);
    if (f.idx === -1) return { success: false, error: 'not_found' };
    var ed = f.list[f.idx];
    if (!Array.isArray(ed.deliveries) || !ed.deliveries[deliveryIdx]) return { success: false, error: 'invalid_delivery_idx' };

    ed.deliveries[deliveryIdx].status = 'delivered';
    ed.deliveries[deliveryIdx].deliveryDate = ed.deliveries[deliveryIdx].deliveryDate || new Date().toISOString();
    ed.updatedAt = new Date().toISOString();

    if (!ed.actualDeliveryDate) ed.actualDeliveryDate = ed.deliveries[deliveryIdx].deliveryDate;

    window._edEnrich(ed);
    if (ed.quantityRemaining === 0) ed.status = 'TESLIM_ALINDI';

    f.list[f.idx] = ed;
    if (typeof window.storeExpectedDeliveries === 'function') window.storeExpectedDeliveries(f.list);
    return { success: true, ed: ed };
  };

  window._edMarkShipped = function(edId, deliveryIdx) {
    var f = _edFindRaw(edId);
    if (f.idx === -1) return { success: false, error: 'not_found' };
    var ed = f.list[f.idx];
    if (!Array.isArray(ed.deliveries) || !ed.deliveries[deliveryIdx]) return { success: false, error: 'invalid_delivery_idx' };
    ed.deliveries[deliveryIdx].status = 'in-transit';
    ed.updatedAt = new Date().toISOString();
    f.list[f.idx] = ed;
    if (typeof window.storeExpectedDeliveries === 'function') window.storeExpectedDeliveries(f.list);
    return { success: true, ed: ed };
  };

  window._edSetDelayOwner = function(edId, owner, reason) {
    if (DELAY_OWNERS.indexOf(owner) === -1) return { success: false, error: 'Geçersiz owner (supplier/logistics/internal)' };
    if (!reason || String(reason).trim().length < 10) return { success: false, error: 'Gecikme sebebi minimum 10 karakter' };
    var f = _edFindRaw(edId);
    if (f.idx === -1) return { success: false, error: 'not_found' };
    f.list[f.idx].delayOwner = owner;
    f.list[f.idx].delayReason = String(reason).trim();
    f.list[f.idx].updatedAt = new Date().toISOString();
    if (typeof window.storeExpectedDeliveries === 'function') window.storeExpectedDeliveries(f.list);
    return { success: true, ed: f.list[f.idx] };
  };

  window._edUpdatePriority = function(edId, priority) {
    if (PRIORITIES.indexOf(priority) === -1) return { success: false, error: 'Geçersiz öncelik' };
    var f = _edFindRaw(edId);
    if (f.idx === -1) return { success: false, error: 'not_found' };
    f.list[f.idx].priority = priority;
    f.list[f.idx].updatedAt = new Date().toISOString();
    if (typeof window.storeExpectedDeliveries === 'function') window.storeExpectedDeliveries(f.list);
    return { success: true, ed: f.list[f.idx] };
  };

  /* ─── PARÇA 2: QUERY HELPERS (PARÇA 6 UI için temel) ────── */
  window._edFilterByStatus = function(status) {
    var all = (typeof window.loadExpectedDeliveries === 'function' ? window.loadExpectedDeliveries() : []) || [];
    return all.filter(function(e) { return e.status === status; });
  };

  window._edFilterOverdue = function() {
    var all = (typeof window.loadExpectedDeliveries === 'function' ? window.loadExpectedDeliveries() : []) || [];
    return all.filter(function(e) { return window._edIsOverdue(e) && e.status !== 'TESLIM_ALINDI'; });
  };

  window._edFilterCritical = function() {
    var all = (typeof window.loadExpectedDeliveries === 'function' ? window.loadExpectedDeliveries() : []) || [];
    return all.filter(function(e) { return e.priority === 'CRITICAL'; });
  };

  window._edFilterUpcoming = function(days) {
    var d = parseInt(days, 10) || 7;
    var all = (typeof window.loadExpectedDeliveries === 'function' ? window.loadExpectedDeliveries() : []) || [];
    return all.filter(function(e) {
      var rem = window._edCalculateRemainingDays(e);
      return rem !== null && rem >= 0 && rem <= d && e.status !== 'TESLIM_ALINDI';
    });
  };

  /* ─── PARÇA 3: SORUMLULUK + CRITICAL BİLDİRİM ────────────── */
  window._edAssignResponsible = function(edId, userId, role) {
    if (!userId || !role) return { success: false, error: 'userId ve role zorunlu' };
    var f = _edFindRaw(edId);
    if (f.idx === -1) return { success: false, error: 'not_found' };
    var ed = f.list[f.idx];

    if (!Array.isArray(ed.responsibleHistory)) ed.responsibleHistory = [];
    if (ed.responsibleUserId && ed.responsibleUserId !== userId) {
      ed.responsibleHistory.push({
        userId: ed.responsibleUserId,
        role: ed.responsibleRole,
        assignedAt: ed.responsibleAssignedAt || ed.createdAt,
        removedAt: new Date().toISOString()
      });
    }
    ed.responsibleUserId = userId;
    ed.responsibleRole = role;
    ed.responsibleAssignedAt = new Date().toISOString();
    ed.updatedAt = new Date().toISOString();

    f.list[f.idx] = ed;
    if (typeof window.storeExpectedDeliveries === 'function') window.storeExpectedDeliveries(f.list);

    try { if (typeof window._edNotifyResponsible === 'function') window._edNotifyResponsible(ed, 'assigned'); } catch(e) {}
    try { if (typeof window.logActivity === 'function') window.logActivity('ed_responsible_assigned', { edId: edId, userId: userId, role: role }); } catch(e) {}
    return { success: true, ed: ed };
  };

  window._edChangeResponsible = function(edId, newUserId, newRole, reason) {
    var f = _edFindRaw(edId);
    if (f.idx === -1) return { success: false, error: 'not_found' };
    var ed = f.list[f.idx];
    var oldUserId = ed.responsibleUserId;
    var oldRole = ed.responsibleRole;
    if (oldUserId === newUserId) return { success: false, error: 'Aynı kullanıcıya zaten atanmış' };

    var result = window._edAssignResponsible(edId, newUserId, newRole);
    if (!result.success) return result;

    try {
      if (oldUserId && typeof window.addNotif === 'function') {
        var _cu = (window.CU && window.CU()) || {};
        if (oldUserId !== (_cu.id || _cu.uid)) {
          window.addNotif(
            'ℹ️',
            'Teslimat sorumluluğu devredildi: ' + (ed.productName || '') + (reason ? ' — ' + reason : ''),
            'info',
            'expected-deliveries',
            oldUserId,
            edId
          );
        }
      }
    } catch(e) {}

    if (reason && String(reason).trim()) {
      var f2 = _edFindRaw(edId);
      if (f2.idx !== -1) {
        if (!Array.isArray(f2.list[f2.idx].responsibleChanges)) f2.list[f2.idx].responsibleChanges = [];
        f2.list[f2.idx].responsibleChanges.push({
          from: { userId: oldUserId, role: oldRole },
          to: { userId: newUserId, role: newRole },
          reason: String(reason).trim(),
          changedAt: new Date().toISOString(),
          changedBy: ((window.CU && window.CU() && (window.CU().id || window.CU().uid)) || 'bilinmiyor')
        });
        if (typeof window.storeExpectedDeliveries === 'function') window.storeExpectedDeliveries(f2.list);
      }
    }
    return { success: true, ed: result.ed };
  };

  var ED_NOTIF_MESSAGES = {
    assigned: { icon: '📦', type: 'info', text: function(ed) { return 'Teslimat sorumluluğu size atandı: ' + (ed.productName || ''); } },
    critical: { icon: '🔴', type: 'err',  text: function(ed) { return 'KRİTİK: ' + (ed.productName || '') + ' teslimatı acil takip'; } },
    overdue:  { icon: '⚠️', type: 'warn', text: function(ed) { return 'Teslimat GECİKTİ: ' + (ed.productName || ''); } },
    reminder: { icon: '⏰', type: 'warn', text: function(ed) { return 'Teslimat yaklaşıyor: ' + (ed.productName || ''); } }
  };

  window._edNotifyResponsible = function(ed, eventType) {
    if (!ed || !ed.responsibleUserId || typeof window.addNotif !== 'function') return;
    var _cu = (window.CU && window.CU()) || {};
    var _cuId = _cu.id || _cu.uid;
    if (ed.responsibleUserId === _cuId) return;

    var _bugun = new Date().toISOString().slice(0, 10);
    var _dedupKey = 'ed_notif_' + ed.id + '_' + ed.responsibleUserId + '_' + eventType + '_' + _bugun;
    try {
      if (localStorage.getItem(_dedupKey)) return;
      localStorage.setItem(_dedupKey, '1');
    } catch(e) {}

    var m = ED_NOTIF_MESSAGES[eventType] || ED_NOTIF_MESSAGES.reminder;
    window.addNotif(m.icon, m.text(ed), m.type, 'expected-deliveries', ed.responsibleUserId, ed.id);

    if (ed.priority === 'CRITICAL' && eventType !== 'critical') {
      try {
        var users = (typeof window.loadUsers === 'function' ? window.loadUsers() : []) || [];
        users.forEach(function(u) {
          if ((u.role || u.rol) !== 'admin') return;
          var _aUid = u.id || u.uid;
          if (!_aUid || _aUid === _cuId) return;
          var _aDedup = 'ed_critical_' + ed.id + '_' + _aUid + '_' + _bugun;
          if (localStorage.getItem(_aDedup)) return;
          localStorage.setItem(_aDedup, '1');
          window.addNotif('🔴', 'KRİTİK teslimat: ' + (ed.productName || ''), 'err', 'expected-deliveries', _aUid, ed.id);
        });
      } catch(e) {}
    }
  };

  window._edGetResponsibleList = function(edId) {
    var all = (typeof window.loadExpectedDeliveries === 'function' ? window.loadExpectedDeliveries({ raw: true }) : []) || [];
    var ed = all.find(function(e) { return e.id === edId; });
    if (!ed) return [];
    var out = [];
    if (ed.responsibleUserId) {
      out.push({
        userId: ed.responsibleUserId,
        role: ed.responsibleRole,
        assignedAt: ed.responsibleAssignedAt || ed.createdAt,
        removedAt: null,
        current: true
      });
    }
    if (Array.isArray(ed.responsibleHistory)) {
      ed.responsibleHistory.forEach(function(h) { out.push(Object.assign({}, h, { current: false })); });
    }
    return out;
  };

  /* _edUpdatePriority override — CRITICAL'a geçişte notify */
  var _origUpdatePriority = window._edUpdatePriority;
  window._edUpdatePriority = function(edId, priority) {
    var result = _origUpdatePriority ? _origUpdatePriority(edId, priority) : { success: false };
    if (result && result.success && priority === 'CRITICAL') {
      try { if (typeof window._edNotifyResponsible === 'function') window._edNotifyResponsible(result.ed, 'critical'); } catch(e) {}
    }
    return result;
  };

  /* Manuel cron — PARÇA 5'te otomatik interval */
  window._edCheckOverdueAndNotify = function() {
    var overdueList = (typeof window._edFilterOverdue === 'function' ? window._edFilterOverdue() : []) || [];
    overdueList.forEach(function(ed) {
      try { if (typeof window._edNotifyResponsible === 'function') window._edNotifyResponsible(ed, 'overdue'); } catch(e) {}
    });
    return { count: overdueList.length };
  };

  /* ─── PARÇA 4: EVENT LISTENERS ──────────────────────────── */
  var _edFindByRef = function(list, d) {
    for (var i = 0; i < list.length; i++) {
      var ed = list[i];
      if (d.edId && ed.id === d.edId) return i;
      if (d.orderId && ed.orderId && ed.orderId === d.orderId) return i;
      if (d.satinalmaId && ed.satinalmaId && ed.satinalmaId === d.satinalmaId) return i;
      if (d.proformaId && ed.proformaId && ed.proformaId === d.proformaId) return i;
    }
    return -1;
  };

  /* AVANS_ODENDI → auto ED create */
  window.addEventListener('AVANS_ODENDI', function(e) {
    try {
      var d = (e && e.detail) || {};
      if (!d.orderId && !d.satinalmaId && !d.proformaId && !d.odemeId) return;

      var existingList = (typeof window.loadExpectedDeliveries === 'function' ? window.loadExpectedDeliveries({ raw: true }) : []) || [];
      if (_edFindByRef(existingList, d) !== -1) {
        console.log('[ED-EVENT] AVANS_ODENDI — zaten kayıt var');
        return;
      }

      var now = new Date();
      var termDays = parseInt(d.deliveryTermDays, 10) || 45;
      var estDelivery = new Date(now.getTime() + termDays * 86400000);
      var _cu = (window.CU && window.CU()) || {};

      var result = window._edCreate({
        orderId: d.orderId,
        satinalmaId: d.satinalmaId,
        proformaId: d.proformaId,
        odemeId: d.odemeId,
        supplierId: d.supplierId || d.cariId || 'bilinmiyor',
        productName: d.productName || 'Tedarikçi siparişi',
        quantityTotal: parseFloat(d.quantity) || 1,
        unit: d.unit || 'adet',
        proformaDate: d.proformaDate || now.toISOString(),
        paymentDate: d.paymentDate || now.toISOString(),
        estimatedDeliveryDate: d.estimatedDeliveryDate || estDelivery.toISOString(),
        deliveryTermDays: termDays,
        toleranceDays: parseInt(d.toleranceDays, 10) || 3,
        priority: d.priority || 'NORMAL',
        status: 'TEDARIK_ASAMASINDA',
        responsibleUserId: d.responsibleUserId || _cu.id || _cu.uid || '1',
        responsibleRole: d.responsibleRole || 'admin',
        autoGenerated: true
      });

      if (result.success) {
        console.log('[ED-EVENT] AVANS_ODENDI → ED oluşturuldu:', result.ed.id);
        try {
          if (typeof window.addNotif === 'function') {
            window.addNotif('📦', 'Tedarikçi siparişi takibe alındı: ' + (d.productName || ''), 'info', 'expected-deliveries', result.ed.responsibleUserId, result.ed.id);
          }
        } catch(ne) {}
      }
    } catch(err) { console.warn('[ED-EVENT AVANS_ODENDI]', err && err.message); }
  });

  /* URUN_SEVK_EDILDI → actualShipmentDate + status YOLDA */
  window.addEventListener('URUN_SEVK_EDILDI', function(e) {
    try {
      var d = (e && e.detail) || {};
      var list = (typeof window.loadExpectedDeliveries === 'function' ? window.loadExpectedDeliveries({ raw: true }) : []) || [];
      var idx = _edFindByRef(list, d);
      if (idx === -1) { console.log('[ED-EVENT] URUN_SEVK_EDILDI — eşleşen ED yok'); return; }

      list[idx].actualShipmentDate = d.shipmentDate || new Date().toISOString();
      var st = list[idx].status;
      if (st === 'TEDARIK_ASAMASINDA' || st === 'URETIMDE' || st === 'YUKLEME_BEKLIYOR') {
        list[idx].status = 'YOLDA';
      }
      list[idx].updatedAt = new Date().toISOString();
      window._edEnrich(list[idx]);
      if (typeof window.storeExpectedDeliveries === 'function') window.storeExpectedDeliveries(list);

      console.log('[ED-EVENT] URUN_SEVK_EDILDI → ED güncellendi:', list[idx].id);
      try { if (typeof window._edNotifyResponsible === 'function') window._edNotifyResponsible(list[idx], 'reminder'); } catch(ne) {}
    } catch(err) { console.warn('[ED-EVENT URUN_SEVK_EDILDI]', err && err.message); }
  });

  /* MAL_TESLIM_EDILDI → deliveries[] ekle */
  window.addEventListener('MAL_TESLIM_EDILDI', function(e) {
    try {
      var d = (e && e.detail) || {};
      if (!d.edId && !d.orderId && !d.satinalmaId) return;
      var list = (typeof window.loadExpectedDeliveries === 'function' ? window.loadExpectedDeliveries({ raw: true }) : []) || [];
      var idx = _edFindByRef(list, d);
      if (idx === -1) { console.log('[ED-EVENT] MAL_TESLIM_EDILDI — eşleşen ED yok'); return; }

      var qty = parseFloat(d.qty);
      if (isNaN(qty)) qty = parseFloat(d.quantity) || 0;
      if (qty <= 0) { console.warn('[ED-EVENT] MAL_TESLIM_EDILDI — qty geçersiz'); return; }

      var addResult = window._edAddDelivery(list[idx].id, {
        qty: qty,
        shipmentDate: d.shipmentDate || list[idx].actualShipmentDate,
        deliveryDate: d.deliveryDate || new Date().toISOString(),
        status: 'delivered'
      });

      if (addResult && addResult.success) {
        var freshList = (typeof window.loadExpectedDeliveries === 'function' ? window.loadExpectedDeliveries({ raw: true }) : []) || [];
        var fIdx = -1;
        for (var i = 0; i < freshList.length; i++) { if (freshList[i].id === list[idx].id) { fIdx = i; break; } }
        if (fIdx !== -1 && freshList[fIdx].quantityRemaining === 0) {
          freshList[fIdx].status = 'TESLIM_ALINDI';
          freshList[fIdx].actualDeliveryDate = freshList[fIdx].actualDeliveryDate || d.deliveryDate || new Date().toISOString();
          if (typeof window.storeExpectedDeliveries === 'function') window.storeExpectedDeliveries(freshList);
        }
        console.log('[ED-EVENT] MAL_TESLIM_EDILDI → teslimat eklendi:', list[idx].id);
      }
    } catch(err) { console.warn('[ED-EVENT MAL_TESLIM_EDILDI]', err && err.message); }
  });

  /* CARI_ONAYLANDI → info log + pending ED count (tedarikçi aktifleşti) */
  window.addEventListener('CARI_ONAYLANDI', function(e) {
    try {
      var d = (e && e.detail) || {};
      var list = (typeof window.loadExpectedDeliveries === 'function' ? window.loadExpectedDeliveries({ raw: true }) : []) || [];
      var count = 0;
      list.forEach(function(ed) {
        if (ed.supplierId === d.cariId && ed.status === 'TEDARIK_ASAMASINDA') count++;
      });
      console.log('[ED-EVENT] CARI_ONAYLANDI (info) —', d.name || d.cariId, '· pending ED:', count);
    } catch(err) { console.warn('[ED-EVENT CARI_ONAYLANDI]', err && err.message); }
  });

  /* ─── PARÇA 5: HATIRLATMA MOTORU ────────────────────────── */
  window._edHatirlatmaTrigger = function(ed) {
    var rem = window._edCalculateRemainingDays(ed);
    if (rem === null) return null;
    if (window._edIsOverdue(ed)) return 'overdue';
    if (rem === 15) return '15day';
    if (rem === 7)  return '7day';
    if (rem === 4)  return '4day';
    if (rem === 1)  return '1day';
    return null;
  };

  var _TASK_TRIGGERS = ['7day', '4day', '1day', 'overdue'];

  window._edHatirlatmaKontrol = function() {
    var list = ((typeof window.loadExpectedDeliveries === 'function' ? window.loadExpectedDeliveries() : []) || [])
      .filter(function(ed) { return ed && ed.status !== 'TESLIM_ALINDI'; });

    var results = { total: 0, notif: 0, task: 0 };
    var bugun = new Date().toISOString().slice(0, 10);

    list.forEach(function(ed) {
      var trig = window._edHatirlatmaTrigger(ed);
      if (!trig) return;
      results.total++;

      var key = 'ed_hatirlatma_' + ed.id + '_' + trig + '_' + bugun;
      try {
        if (localStorage.getItem(key)) return;
        localStorage.setItem(key, '1');
      } catch(e) {}

      try {
        if (typeof window._edNotifyResponsible === 'function') {
          window._edNotifyResponsible(ed, trig === 'overdue' ? 'overdue' : 'reminder');
          results.notif++;
        }
      } catch(e) {}

      if (_TASK_TRIGGERS.indexOf(trig) !== -1 && typeof window.addTask === 'function') {
        try {
          window.addTask({
            title: 'Teslimat takip: ' + (ed.productName || '') + ' (' + trig + ')',
            deliveryId: ed.id,
            assignedRole: ed.responsibleRole,
            assignedUser: ed.responsibleUserId,
            dueDate: ed.estimatedDeliveryDate,
            priority: ed.priority === 'CRITICAL' ? 'high' : 'normal',
            autoGenerated: true,
            source: 'expected_deliveries'
          });
          results.task++;
        } catch(e) {}
      }
    });
    return results;
  };

  window._edHatirlatmaBaslat = function() {
    if (window._edHatirlatmaInterval) return;
    setTimeout(function() {
      try { window._edHatirlatmaKontrol(); } catch(e) {}
    }, 10000);
    window._edHatirlatmaInterval = setInterval(function() {
      try { window._edHatirlatmaKontrol(); } catch(e) {}
    }, 5 * 60 * 1000);
  };

  window._edHatirlatmaDurdur = function() {
    if (window._edHatirlatmaInterval) {
      clearInterval(window._edHatirlatmaInterval);
      window._edHatirlatmaInterval = null;
    }
  };

  /* Auto-start */
  window._edHatirlatmaBaslat();

  /* ─── PARÇA 6: UI LİSTE + 4 FİLTRE (Apple minimal) ─────── */
  var _uiEsc = function(s) { return String(s == null ? '' : s).replace(/[&<>"']/g, function(c){ return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]; }); };

  var STATUS_LABELS = {
    TEDARIK_ASAMASINDA: 'Tedarik',
    URETIMDE: 'Üretimde',
    YUKLEME_BEKLIYOR: 'Yükleme',
    YOLDA: 'Yolda',
    GUMRUKTE: 'Gümrükte',
    TESLIM_ALINDI: 'Teslim',
    GECIKTI: 'Gecikti'
  };
  var STATUS_COLORS = {
    TEDARIK_ASAMASINDA: '#888780',
    URETIMDE: '#D97706',
    YUKLEME_BEKLIYOR: '#854F0B',
    YOLDA: '#185FA5',
    GUMRUKTE: '#7C3AED',
    TESLIM_ALINDI: '#16A34A',
    GECIKTI: '#E0574F'
  };
  var PRI_LABELS = { LOW: 'Düşük', NORMAL: 'Normal', CRITICAL: 'Kritik' };
  var PRI_COLORS = { LOW: '#6B7280', NORMAL: '#374151', CRITICAL: '#E0574F' };

  function _edColorByDays(rem) {
    if (rem === null || rem === undefined) return '#9CA3AF';
    if (rem > 15) return '#9CA3AF';
    if (rem >= 7) return '#F59E0B';
    if (rem >= 4) return '#F97316';
    return '#E0574F';
  }

  function _edUserAd(uid) {
    try {
      var users = (typeof window.loadUsers === 'function' ? window.loadUsers() : []) || [];
      var u = users.find(function(x) { return (x.id || x.uid) === uid; });
      return u ? (u.name || u.displayName || u.email || '—') : (uid || '—');
    } catch(e) { return uid || '—'; }
  }

  window._edCurrentFilter = window._edCurrentFilter || 'upcoming';

  window._edSetFilter = function(f) {
    window._edCurrentFilter = f;
    window._edRenderPanel();
  };

  window._edRenderCard = function(ed) {
    var rem = window._edCalculateRemainingDays(ed);
    var remColor = _edColorByDays(rem);
    var remText = rem === null ? 'Tarih yok' : (rem < 0 ? (Math.abs(rem) + ' gün geçti') : (rem === 0 ? 'Bugün' : (rem + ' gün kaldı')));
    var st = ed.status || 'TEDARIK_ASAMASINDA';
    var stColor = STATUS_COLORS[st] || '#888780';
    var stLabel = STATUS_LABELS[st] || st;
    var pri = ed.priority || 'NORMAL';
    var priColor = PRI_COLORS[pri] || '#374151';
    var priLabel = PRI_LABELS[pri] || pri;
    var delivered = ed.quantityDelivered || 0;
    var total = ed.quantityTotal || 0;
    var pct = total > 0 ? Math.min(100, Math.round((delivered / total) * 100)) : 0;
    var etaStr = ed.estimatedDeliveryDate ? new Date(ed.estimatedDeliveryDate).toLocaleDateString('tr-TR') : '—';
    var sorumlu = ed.responsibleUserId ? _edUserAd(ed.responsibleUserId) : '—';

    return '<div style="background:var(--sf,#fff);border:0.5px solid var(--b,#CBD5E1);border-radius:10px;padding:14px 16px;margin-bottom:10px;box-shadow:0 1px 2px rgba(0,0,0,0.04)">'
      + '<div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:8px;gap:10px">'
        + '<div style="display:flex;align-items:center;gap:10px;min-width:0;flex:1">'
          + '<span style="font-size:14px">📦</span>'
          + '<div style="min-width:0;flex:1">'
            + '<div style="font-size:13px;font-weight:500;color:var(--t,#111);white-space:nowrap;overflow:hidden;text-overflow:ellipsis">' + _uiEsc(ed.productName || '—') + '</div>'
            + '<div style="font-size:10px;color:var(--t3,#6B7280);letter-spacing:.02em;margin-top:2px">' + _uiEsc(ed.supplierId || '—') + '</div>'
          + '</div>'
        + '</div>'
        + '<div style="display:flex;gap:4px;flex-shrink:0">'
          + '<span style="font-size:9px;padding:2px 8px;border-radius:10px;background:' + stColor + '22;color:' + stColor + ';font-weight:500;letter-spacing:.04em">' + _uiEsc(stLabel).toUpperCase() + '</span>'
          + (pri === 'CRITICAL' ? '<span style="font-size:9px;padding:2px 8px;border-radius:10px;background:' + priColor + '22;color:' + priColor + ';font-weight:600;letter-spacing:.04em">⚠ ' + _uiEsc(priLabel).toUpperCase() + '</span>' : '')
        + '</div>'
      + '</div>'
      + '<div style="display:flex;align-items:center;gap:14px;margin-bottom:8px;flex-wrap:wrap">'
        + '<div style="font-size:11px;color:' + remColor + ';font-weight:500">' + remText + '</div>'
        + '<div style="font-size:10px;color:var(--t3,#6B7280);font-variant-numeric:tabular-nums">' + delivered + '/' + total + ' ' + _uiEsc(ed.unit || '') + '</div>'
      + '</div>'
      + '<div style="height:4px;background:var(--s2,#F1F5F9);border-radius:2px;overflow:hidden;margin-bottom:10px">'
        + '<div style="height:100%;width:' + pct + '%;background:' + stColor + ';transition:width .3s"></div>'
      + '</div>'
      + '<div style="display:flex;align-items:center;justify-content:space-between;gap:8px;flex-wrap:wrap">'
        + '<div style="font-size:10px;color:var(--t3,#6B7280)">🗓 ' + etaStr + ' · 👤 ' + _uiEsc(sorumlu) + '</div>'
        + '<div style="display:flex;gap:4px">'
          + '<button onclick="window._edOpenDetail && window._edOpenDetail(\'' + _uiEsc(ed.id) + '\')" style="font-size:10px;padding:4px 10px;border:0.5px solid var(--b,#CBD5E1);background:transparent;border-radius:6px;cursor:pointer;font-family:inherit;color:var(--t2,#374151)">Detay</button>'
          + (ed.status !== 'TESLIM_ALINDI' ? '<button onclick="window._edAddDeliveryPrompt && window._edAddDeliveryPrompt(\'' + _uiEsc(ed.id) + '\')" style="font-size:10px;padding:4px 10px;border:none;background:#1A8D6F;color:#fff;border-radius:6px;cursor:pointer;font-family:inherit;font-weight:500">+ Teslimat</button>' : '')
        + '</div>'
      + '</div>'
    + '</div>';
  };

  window._edAddDeliveryPrompt = function(edId) {
    var qtyStr = window.prompt('Eklenecek teslim miktarı:', '');
    if (qtyStr === null) return;
    var qty = parseFloat(qtyStr);
    if (isNaN(qty) || qty <= 0) { if (window.toast) window.toast('Geçersiz miktar', 'err'); return; }
    var r = window._edAddDelivery(edId, { qty: qty, deliveryDate: new Date().toISOString(), status: 'delivered' });
    if (r && r.success) {
      if (window.toast) window.toast('Teslimat eklendi', 'ok');
      window._edRenderPanel();
    } else {
      if (window.toast) window.toast((r && r.error) || 'Ekleme hatası', 'err');
    }
  };

  window._edOpenDetail = function(edId) {
    var all = (typeof window.loadExpectedDeliveries === 'function' ? window.loadExpectedDeliveries({ raw: true }) : []) || [];
    var ed = all.find(function(e) { return e.id === edId; });
    if (!ed) { if (window.toast) window.toast('Kayıt bulunamadı', 'err'); return; }
    var deliveries = (ed.deliveries || []).map(function(d, i) {
      return '<tr style="border-bottom:0.5px solid var(--b)"><td style="padding:6px 8px;font-size:11px">' + (i + 1) + '</td><td style="padding:6px 8px;font-size:11px;font-variant-numeric:tabular-nums">' + (d.qty || 0) + '</td><td style="padding:6px 8px;font-size:11px">' + (d.shipmentDate ? new Date(d.shipmentDate).toLocaleDateString('tr-TR') : '—') + '</td><td style="padding:6px 8px;font-size:11px">' + (d.deliveryDate ? new Date(d.deliveryDate).toLocaleDateString('tr-TR') : '—') + '</td><td style="padding:6px 8px;font-size:10px;color:var(--t3)">' + _uiEsc(d.status || '—') + '</td></tr>';
    }).join('') || '<tr><td colspan="5" style="padding:20px;text-align:center;color:var(--t3);font-size:11px">Teslimat kaydı yok</td></tr>';
    var ex = document.getElementById('ed-detail-modal'); if (ex) ex.remove();
    var mo = document.createElement('div');
    mo.id = 'ed-detail-modal';
    mo.style.cssText = 'position:fixed;inset:0;background:rgba(0,0,0,.4);z-index:10000;display:flex;align-items:center;justify-content:center';
    mo.onclick = function(e) { if (e.target === mo) mo.remove(); };
    mo.innerHTML = '<div style="background:var(--sf,#fff);color:var(--t,#111);width:640px;max-width:92vw;max-height:90vh;overflow-y:auto;border-radius:12px;padding:24px;box-shadow:0 20px 60px rgba(0,0,0,.15);font-family:inherit">'
      + '<div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:16px"><div style="font-size:15px;font-weight:600">📦 ' + _uiEsc(ed.productName || '—') + '</div><button onclick="document.getElementById(\'ed-detail-modal\').remove()" style="background:none;border:none;font-size:18px;color:var(--t3);cursor:pointer">×</button></div>'
      + '<div style="display:grid;grid-template-columns:1fr 1fr 1fr;gap:10px;margin-bottom:16px">'
        + '<div><div style="font-size:9px;color:var(--t3);text-transform:uppercase;letter-spacing:.05em">Tedarikçi</div><div style="font-size:12px;margin-top:2px">' + _uiEsc(ed.supplierId || '—') + '</div></div>'
        + '<div><div style="font-size:9px;color:var(--t3);text-transform:uppercase;letter-spacing:.05em">Sorumlu</div><div style="font-size:12px;margin-top:2px">' + _uiEsc(_edUserAd(ed.responsibleUserId)) + '</div></div>'
        + '<div><div style="font-size:9px;color:var(--t3);text-transform:uppercase;letter-spacing:.05em">Durum</div><div style="font-size:12px;margin-top:2px;color:' + (STATUS_COLORS[ed.status] || '#888780') + ';font-weight:500">' + _uiEsc(STATUS_LABELS[ed.status] || ed.status || '—') + '</div></div>'
        + '<div><div style="font-size:9px;color:var(--t3);text-transform:uppercase;letter-spacing:.05em">Toplam</div><div style="font-size:12px;margin-top:2px;font-variant-numeric:tabular-nums">' + (ed.quantityTotal || 0) + ' ' + _uiEsc(ed.unit || '') + '</div></div>'
        + '<div><div style="font-size:9px;color:var(--t3);text-transform:uppercase;letter-spacing:.05em">Teslim</div><div style="font-size:12px;margin-top:2px;font-variant-numeric:tabular-nums">' + (ed.quantityDelivered || 0) + '</div></div>'
        + '<div><div style="font-size:9px;color:var(--t3);text-transform:uppercase;letter-spacing:.05em">Kalan</div><div style="font-size:12px;margin-top:2px;font-variant-numeric:tabular-nums">' + (ed.quantityRemaining || 0) + '</div></div>'
        + '<div><div style="font-size:9px;color:var(--t3);text-transform:uppercase;letter-spacing:.05em">Tahmini Teslim</div><div style="font-size:12px;margin-top:2px">' + (ed.estimatedDeliveryDate ? new Date(ed.estimatedDeliveryDate).toLocaleDateString('tr-TR') : '—') + '</div></div>'
        + '<div><div style="font-size:9px;color:var(--t3);text-transform:uppercase;letter-spacing:.05em">Öncelik</div><div style="font-size:12px;margin-top:2px;color:' + (PRI_COLORS[ed.priority] || '#374151') + ';font-weight:500">' + _uiEsc(PRI_LABELS[ed.priority] || ed.priority || '—') + '</div></div>'
        + '<div><div style="font-size:9px;color:var(--t3);text-transform:uppercase;letter-spacing:.05em">Tolerans</div><div style="font-size:12px;margin-top:2px">' + (ed.toleranceDays || 0) + ' gün</div></div>'
      + '</div>'
      + (ed.delayReason ? '<div style="margin-bottom:16px;padding:10px;background:#FEF2F2;border:0.5px solid #FECACA;border-radius:8px;font-size:11px;color:#991B1B">⚠ <b>Gecikme:</b> ' + _uiEsc(ed.delayOwner || '—') + ' — ' + _uiEsc(ed.delayReason) + '</div>' : '')
      + '<div style="font-size:10px;color:var(--t3);text-transform:uppercase;letter-spacing:.05em;margin-bottom:6px">Teslimat Geçmişi</div>'
      + '<table style="width:100%;border-collapse:collapse;margin-bottom:16px"><thead><tr style="background:var(--s2,#F1F5F9);font-size:9px;color:var(--t3);text-transform:uppercase;letter-spacing:.05em"><th style="padding:6px 8px;text-align:left">#</th><th style="padding:6px 8px;text-align:left">Miktar</th><th style="padding:6px 8px;text-align:left">Sevk</th><th style="padding:6px 8px;text-align:left">Teslim</th><th style="padding:6px 8px;text-align:left">Durum</th></tr></thead><tbody>' + deliveries + '</tbody></table>'
      + (ed.autoGenerated ? '<div style="font-size:9px;color:var(--t3);text-align:center;padding-top:8px;border-top:0.5px solid var(--b)">🤖 Otomatik oluşturuldu · ' + (ed.createdAt ? new Date(ed.createdAt).toLocaleDateString('tr-TR') : '—') + '</div>' : '')
    + '</div>';
    document.body.appendChild(mo);
  };

  window._edRenderPanel = function() {
    var p = document.getElementById('panel-teslimat-takip');
    if (!p) return;

    var all = (typeof window.loadExpectedDeliveries === 'function' ? window.loadExpectedDeliveries() : []) || [];
    var counts = {
      total: all.length,
      upcoming: (typeof window._edFilterUpcoming === 'function' ? window._edFilterUpcoming(7) : []).length,
      overdue: (typeof window._edFilterOverdue === 'function' ? window._edFilterOverdue() : []).length,
      critical: (typeof window._edFilterCritical === 'function' ? window._edFilterCritical() : []).length,
      done: all.filter(function(e) { return e.status === 'TESLIM_ALINDI'; }).length
    };

    var filter = window._edCurrentFilter || 'upcoming';
    var shown = [];
    if (filter === 'upcoming') shown = (typeof window._edFilterUpcoming === 'function' ? window._edFilterUpcoming(7) : []);
    else if (filter === 'overdue') shown = (typeof window._edFilterOverdue === 'function' ? window._edFilterOverdue() : []);
    else if (filter === 'critical') shown = (typeof window._edFilterCritical === 'function' ? window._edFilterCritical() : []);
    else if (filter === 'done') shown = all.filter(function(e) { return e.status === 'TESLIM_ALINDI'; });
    else shown = all;

    var mode = window.EXPECTED_DELIVERIES_MODE || 'MANUAL_MODE';
    var modeColor = mode === 'AUTO_MODE' ? '#185FA5' : '#6B7280';

    var filterBtn = function(key, label, count) {
      var active = filter === key;
      return '<button onclick="window._edSetFilter(\'' + key + '\')" style="padding:7px 14px;border:none;background:' + (active ? 'var(--t,#111)' : 'transparent') + ';color:' + (active ? '#fff' : 'var(--t2,#374151)') + ';border-radius:8px;font-size:11px;font-weight:' + (active ? '500' : '400') + ';cursor:pointer;font-family:inherit;letter-spacing:.02em;transition:all .15s">' + label + ' <span style="font-variant-numeric:tabular-nums;opacity:.7">' + count + '</span></button>';
    };

    p.innerHTML = '<div style="padding:0;font-family:inherit">'
      + '<div style="padding:18px 24px;border-bottom:0.5px solid var(--b,#CBD5E1);display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:10px">'
        + '<div>'
          + '<div style="font-size:16px;font-weight:600;color:var(--t,#111);display:flex;align-items:center;gap:10px">🚚 Teslimat Takibi <span style="font-size:9px;padding:2px 8px;border-radius:10px;background:' + modeColor + '22;color:' + modeColor + ';font-weight:500;letter-spacing:.04em">' + mode.replace('_', ' ') + '</span></div>'
          + '<div style="font-size:11px;color:var(--t3,#6B7280);margin-top:3px">Toplam: <b>' + counts.total + '</b> · Yaklaşan: <b style="color:#F59E0B">' + counts.upcoming + '</b> · Gecikmiş: <b style="color:#E0574F">' + counts.overdue + '</b> · Kritik: <b style="color:#E0574F">' + counts.critical + '</b></div>'
        + '</div>'
      + '</div>'
      + '<div style="padding:14px 24px;border-bottom:0.5px solid var(--b,#CBD5E1);display:flex;gap:4px;flex-wrap:wrap;background:var(--s2,#F1F5F9)">'
        + filterBtn('upcoming', 'Yaklaşan', counts.upcoming)
        + filterBtn('overdue', 'Gecikenler', counts.overdue)
        + filterBtn('critical', 'Kritik', counts.critical)
        + filterBtn('done', 'Tamamlanan', counts.done)
        + filterBtn('all', 'Tümü', counts.total)
      + '</div>'
      + '<div style="padding:16px 24px">'
        + (shown.length
            ? shown.map(function(ed) { return window._edRenderCard(ed); }).join('')
            : '<div style="padding:40px 20px;text-align:center;color:var(--t3,#9CA3AF);font-size:13px">Bu filtrede kayıt yok</div>')
      + '</div>'
    + '</div>';
  };
})();
